export const FETCH_GET_EXAMEN_MEDICO_INIT = "FETCH_GET_EXAMEN_MEDICO_INIT";
export const FETCH_GET_EXAMEN_MEDICO_SUCCESS =
  "FETCH_GET_EXAMEN_MEDICO_SUCCESS";
export const FETCH_GET_EXAMEN_MEDICO_FAILURE =
  "FETCH_GET_EXAMEN_MEDICO_FAILURE";

export const UPDATE_EXAMEN_MEDICO_INIT = "UPDATE_EXAMEN_MEDICO_INIT";
export const UPDATE_EXAMEN_MEDICO_SUCCESS = "UPDATE_EXAMEN_MEDICO_SUCCESS";
export const UPDATE_EXAMEN_MEDICO_FAILURE = "UPDATE_EXAMEN_MEDICO_FAILURE";

export const RESET_GET_EXAMEN_MEDICO = "RESET_GET_TRABAJADOR_EMPRESA";
