export const FETCH_LIST_USER_INIT = "FETCH_LIST_USER_INIT";
export const FETCH_LIST_USER_SUCCESS = "FETCH_LIST_USER_SUCCESS";
export const FETCH_LIST_USER_FAILURE = "FETCH_LIST_USER_FAILURE";

export const DELETE_USER_INIT = "  DELETE_USER_INIT";
export const DELETE_USER_SUCCESS = "  DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "  DELETE_USER_FAILURE";

export const RESET_LIST_USER = " RESET_LIST_USER";
export const RESET_MODAL_USER = " RESET_MODAL_USER";
