export const FETCH_LIST_USER_INIT = "FETCH_LIST_USER_INIT";
export const FETCH_LIST_USER_SUCCESS = "FETCH_LIST_USER_SUCCESS";
export const FETCH_LIST_USER_FAILURE = "FETCH_LIST_USER_FAILURE";

export const RESET_LIST_USER = " RESET_LIST_USER";
