export const FETCH_LIST_OXIMETRIA_INFO_INIT = "FETCH_LIST_OXIMETRIA_INFO_INIT";
export const FETCH_LIST_OXIMETRIA_INFO_SUCCESS =
  "FETCH_LIST_OXIMETRIA_INFO_SUCCESS";
export const FETCH_LIST_OXIMETRIA_INFO_FAILURE =
  "FETCH_LIST_OXIMETRIA_INFO_FAILURE";

export const SAVE_OXIMETRIA_INIT = "SAVE_OXIMETRIA_INIT";
export const SAVE_OXIMETRIA_SUCCESS = "SAVE_OXIMETRIA_SUCCESS";
export const SAVE_OXIMETRIA_FAILURE = "SAVE_OXIMETRIA_FAILURE";

export const RESET_LIST_OXIMETRIA_INFO = "RESET_LIST_OXIMETRIA_INFO";
export const RESET_MODAL_OXIMETRIA = " RESET_MODAL_OXIMETRIA";
