export const FETCH_LIST_SURVEYS_EPWORTH_INIT =
  "FETCH_LIST_SURVEYS_EPWORTH_INIT";
export const FETCH_LIST_SURVEYS_EPWORTH_SUCCESS =
  "FETCH_LIST_SURVEYS_EPWORTH_SUCCESS";
export const FETCH_LIST_SURVEYS_EPWORTH_FAILURE =
  "FETCH_LIST_SURVEYS_EPWORTH_FAILURE";

export const SAVE_SURVEYS_EPWORTH_INIT = "SAVE_SURVEYS_EPWORTH_INIT";
export const SAVE_SURVEYS_EPWORTH_SUCCESS = "SAVE_SURVEYS_EPWORTH_SUCCESS";
export const SAVE_SURVEYS_EPWORTH_FAILURE = "SAVE_SURVEYS_EPWORTH_FAILURE";

export const RESET_LIST_SURVEYS_EPWORTH = " RESET_LIST_SURVEYS_EPWORTH";
export const RESET_MODAL_SURVEYS_EPWORTH = " RESET_MODAL_SURVEYS_EPWORTH";
