export const FETCH_LIST_POLISOMNOGRAFIA_INIT =
  "FETCH_LIST_POLISOMNOGRAFIA_INIT";
export const FETCH_LIST_POLISOMNOGRAFIA_SUCCESS =
  "FETCH_LIST_POLISOMNOGRAFIA_SUCCESS";
export const FETCH_LIST_POLISOMNOGRAFIA_FAILURE =
  "FETCH_LIST_POLISOMNOGRAFIA_FAILURE";

export const FETCH_LIST_POLISOMNOGRAFIA_COUNT_INIT =
  "FETCH_LIST_POLISOMNOGRAFIA_COUNT_INIT";
export const FETCH_LIST_POLISOMNOGRAFIA_COUNT_SUCCESS =
  "FETCH_LIST_POLISOMNOGRAFIA_COUNT_SUCCESS";
export const FETCH_LIST_POLISOMNOGRAFIA_COUNT_FAILURE =
  "FETCH_LIST_POLISOMNOGRAFIA_COUNT_FAILURE";

export const DELETE_POLISOMNOGRAFIA_INIT = "  DELETE_POLISOMNOGRAFIA_INIT";
export const DELETE_POLISOMNOGRAFIA_SUCCESS =
  "  DELETE_POLISOMNOGRAFIA_SUCCESS";
export const DELETE_POLISOMNOGRAFIA_FAILURE =
  "  DELETE_POLISOMNOGRAFIA_FAILURE";

export const RESET_LIST_POLISOMNOGRAFIA = " RESET_LIST_POLISOMNOGRAFIA";
export const RESET_MODAL_POLISOMNOGRAFIA = " RESET_MODAL_POLISOMNOGRAFIA";
