export const FETCH_GET_POLISOMNOGRAFIA_INIT = "FETCH_GET_POLISOMNOGRAFIA_INIT";
export const FETCH_GET_POLISOMNOGRAFIA_SUCCESS =
  "FETCH_GET_POLISOMNOGRAFIA_SUCCESS";
export const FETCH_GET_POLISOMNOGRAFIA_FAILURE =
  "FETCH_GET_POLISOMNOGRAFIA_FAILURE";

export const UPDATE_POLISOMNOGRAFIA_INIT = "UPDATE_POLISOMNOGRAFIA_INIT";
export const UPDATE_POLISOMNOGRAFIA_SUCCESS = "UPDATE_POLISOMNOGRAFIA_SUCCESS";
export const UPDATE_POLISOMNOGRAFIA_FAILURE = "UPDATE_POLISOMNOGRAFIA_FAILURE";

export const RESET_GET_POLISOMNOGRAFIA = "RESET_GET_POLISOMNOGRAFIA";
