export const RESET_LOGIN = "RESET_LOGIN";
export const LOG_OUT = "LOG_OUT";

/* (ASYNC) */
export const SAVE_LOGIN_INIT = "SAVE_LOGIN_INIT";
export const SAVE_LOGIN_SUCCESS = "SAVE_LOGIN_SUCCESS";
export const SAVE_LOGIN_FAILURE = "SAVE_LOGIN_FAILURE";

export const SAVE_REGISTER_INIT = "SAVE_REGISTER_INIT";
export const SAVE_REGISTER_SUCCESS = "SAVE_REGISTER_SUCCESS";
export const SAVE_REGISTER_FAILURE = "SAVE_REGISTER_FAILURE";

export const SAVE_FORGET_INIT = "SAVE_FORGET_INIT";
export const SAVE_FORGET_SUCCESS = "SAVE_FORGET_SUCCESS";
export const SAVE_FORGET_FAILURE = "SAVE_FORGET_FAILURE";
