export const FETCH_LIST_TRABAJADOR_EMPRESA_INIT =
  "FETCH_LIST_TRABAJADOR_EMPRESA_INIT";
export const FETCH_LIST_TRABAJADOR_EMPRESA_SUCCESS =
  "FETCH_LIST_TRABAJADOR_EMPRESA_SUCCESS";
export const FETCH_LIST_TRABAJADOR_EMPRESA_FAILURE =
  "FETCH_LIST_TRABAJADOR_EMPRESA_FAILURE";

export const FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_INIT =
  "FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_INIT";
export const FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_SUCCESS =
  "FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_SUCCESS";
export const FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_FAILURE =
  "FETCH_LIST_TRABAJADOR_EMPRESA_COUNT_FAILURE";

export const DELETE_TRABAJADOR_EMPRESA_INIT =
  "  DELETE_TRABAJADOR_EMPRESA_INIT";
export const DELETE_TRABAJADOR_EMPRESA_SUCCESS =
  "  DELETE_TRABAJADOR_EMPRESA_SUCCESS";
export const DELETE_TRABAJADOR_EMPRESA_FAILURE =
  "  DELETE_TRABAJADOR_EMPRESA_FAILURE";

export const RESET_LIST_TRABAJADOR_EMPRESA = " RESET_LIST_TRABAJADOR_EMPRESA";
export const RESET_MODAL_TRABAJADOR_EMPRESA = " RESET_MODAL_TRABAJADOR_EMPRESA";
