export const FETCH_GET_DATOS_PERSONALES_INIT =
  "FETCH_GET_DATOS_PERSONALES_INIT";
export const FETCH_GET_DATOS_PERSONALES_SUCCESS =
  "FETCH_GET_DATOS_PERSONALES_SUCCESS";
export const FETCH_GET_DATOS_PERSONALES_FAILURE =
  "FETCH_GET_DATOS_PERSONALES_FAILURE";

export const UPDATE_DATOS_PERSONALES_INIT = "UPDATE_DATOS_PERSONALES_INIT";
export const UPDATE_DATOS_PERSONALES_SUCCESS =
  "UPDATE_DATOS_PERSONALES_SUCCESS";
export const UPDATE_DATOS_PERSONALES_FAILURE =
  "UPDATE_DATOS_PERSONALES_FAILURE";

export const RESET_GET_DATOS_PERSONALES = "RESET_GET_DATOS_PERSONALES";
