export const FETCH_LIST_DATOS_PERSONALES_INFO_INIT =
  "FETCH_LIST_DATOS_PERSONALES_INFO_INIT";
export const FETCH_LIST_DATOS_PERSONALES_INFO_SUCCESS =
  "FETCH_LIST_DATOS_PERSONALES_INFO_SUCCESS";
export const FETCH_LIST_DATOS_PERSONALES_INFO_FAILURE =
  "FETCH_LIST_DATOS_PERSONALES_INFO_FAILURE";

export const RESET_LIST_DATOS_PERSONALES_INFO =
  "RESET_LIST_DATOS_PERSONALES_INFO";
