export const FETCH_GET_USER_INIT = "FETCH_GET_USER_INIT";
export const FETCH_GET_USER_SUCCESS = "FETCH_GET_USER_SUCCESS";
export const FETCH_GET_USER_FAILURE = "FETCH_GET_USER_FAILURE";

export const UPDATE_USER_INIT = "UPDATE_USER_INIT";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const RESET_GET_USER = " RESET_GET_USER";
