export const FETCH_LIST_DATOS_PERSONALES_INIT =
  "FETCH_LIST_DATOS_PERSONALES_INIT";
export const FETCH_LIST_DATOS_PERSONALES_SUCCESS =
  "FETCH_LIST_DATOS_PERSONALES_SUCCESS";
export const FETCH_LIST_DATOS_PERSONALES_FAILURE =
  "FETCH_LIST_DATOS_PERSONALES_FAILURE";

export const FETCH_LIST_DATOS_PERSONALES_COUNT_INIT =
  "FETCH_LIST_DATOS_PERSONALES_COUNT_INIT";
export const FETCH_LIST_DATOS_PERSONALES_COUNT_SUCCESS =
  "FETCH_LIST_DATOS_PERSONALES_COUNT_SUCCESS";
export const FETCH_LIST_DATOS_PERSONALES_COUNT_FAILURE =
  "FETCH_LIST_DATOS_PERSONALES_COUNT_FAILURE";

export const DELETE_DATOS_PERSONALES_INIT = "  DELETE_DATOS_PERSONALES_INIT";
export const DELETE_DATOS_PERSONALES_SUCCESS =
  "  DELETE_DATOS_PERSONALES_SUCCESS";
export const DELETE_DATOS_PERSONALES_FAILURE =
  "  DELETE_DATOS_PERSONALES_FAILURE";

export const RESET_LIST_DATOS_PERSONALES = " RESET_LIST_DATOS_PERSONALES";
export const RESET_MODAL_DATOS_PERSONALES = " RESET_MODAL_DATOS_PERSONALES";
