export const FETCH_LIST_OXIMETRIA_INIT = "FETCH_LIST_OXIMETRIA_INIT";
export const FETCH_LIST_OXIMETRIA_SUCCESS = "FETCH_LIST_OXIMETRIA_SUCCESS";
export const FETCH_LIST_OXIMETRIA_FAILURE = "FETCH_LIST_OXIMETRIA_FAILURE";

export const FETCH_LIST_OXIMETRIA_COUNT_INIT =
  "FETCH_LIST_OXIMETRIA_COUNT_INIT";
export const FETCH_LIST_OXIMETRIA_COUNT_SUCCESS =
  "FETCH_LIST_OXIMETRIA_COUNT_SUCCESS";
export const FETCH_LIST_OXIMETRIA_COUNT_FAILURE =
  "FETCH_LIST_OXIMETRIA_COUNT_FAILURE";

export const DELETE_OXIMETRIA_INIT = "  DELETE_OXIMETRIA_INIT";
export const DELETE_OXIMETRIA_SUCCESS = "  DELETE_OXIMETRIA_SUCCESS";
export const DELETE_OXIMETRIA_FAILURE = "  DELETE_OXIMETRIA_FAILURE";

export const RESET_LIST_OXIMETRIA = " RESET_LIST_OXIMETRIA";
export const RESET_MODAL_OXIMETRIA = " RESET_MODAL_OXIMETRIA";
