export const FETCH_HOME_INIT = "FETCH_HOME_INIT";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_FAILURE = "FETCH_HOME_FAILURE";

export const FETCH_HOME_GRAPH_INIT = "FETCH_HOME_GRAPH_INIT";
export const FETCH_HOME_GRAPH_SUCCESS = "FETCH_HOME_GRAPH_SUCCESS";
export const FETCH_HOME_GRAPH_FAILURE = "FETCH_HOME_GRAPH_FAILURE";
