export const FETCH_GET_TRABAJADOR_EMPRESA_INIT =
  "FETCH_GET_TRABAJADOR_EMPRESA_INIT";
export const FETCH_GET_TRABAJADOR_EMPRESA_SUCCESS =
  "FETCH_GET_TRABAJADOR_EMPRESA_SUCCESS";
export const FETCH_GET_TRABAJADOR_EMPRESA_FAILURE =
  "FETCH_GET_TRABAJADOR_EMPRESA_FAILURE";

export const UPDATE_TRABAJADOR_EMPRESA_INIT = "UPDATE_TRABAJADOR_EMPRESA_INIT";
export const UPDATE_TRABAJADOR_EMPRESA_SUCCESS =
  "UPDATE_TRABAJADOR_EMPRESA_SUCCESS";
export const UPDATE_TRABAJADOR_EMPRESA_FAILURE =
  "UPDATE_TRABAJADOR_EMPRESA_FAILURE";

export const RESET_GET_TRABAJADOR_EMPRESA = "RESET_GET_TRABAJADOR_EMPRESA";
