export const FETCH_LIST_EXAMEN_MEDICO_INIT = "FETCH_LIST_EXAMEN_MEDICO_INIT";
export const FETCH_LIST_EXAMEN_MEDICO_SUCCESS =
  "FETCH_LIST_EXAMEN_MEDICO_SUCCESS";
export const FETCH_LIST_EXAMEN_MEDICO_FAILURE =
  "FETCH_LIST_EXAMEN_MEDICO_FAILURE";

export const FETCH_LIST_EXAMEN_MEDICO_COUNT_INIT =
  "FETCH_LIST_EXAMEN_MEDICO_COUNT_INIT";
export const FETCH_LIST_EXAMEN_MEDICO_COUNT_SUCCESS =
  "FETCH_LIST_EXAMEN_MEDICO_COUNT_SUCCESS";
export const FETCH_LIST_EXAMEN_MEDICO_COUNT_FAILURE =
  "FETCH_LIST_EXAMEN_MEDICO_COUNT_FAILURE";

export const DELETE_EXAMEN_MEDICO_INIT = "  DELETE_EXAMEN_MEDICO_INIT";
export const DELETE_EXAMEN_MEDICO_SUCCESS = "  DELETE_EXAMEN_MEDICO_SUCCESS";
export const DELETE_EXAMEN_MEDICO_FAILURE = "  DELETE_EXAMEN_MEDICO_FAILURE";

export const RESET_LIST_EXAMEN_MEDICO = " RESET_LIST_EXAMEN_MEDICO";
export const RESET_MODAL_EXAMEN_MEDICO = " RESET_MODAL_EXAMEN_MEDICO";
