export const FETCH_LIST_EXAMEN_FISICO_INIT = "FETCH_LIST_EXAMEN_FISICO_INIT";
export const FETCH_LIST_EXAMEN_FISICO_SUCCESS =
  "FETCH_LIST_EXAMEN_FISICO_SUCCESS";
export const FETCH_LIST_EXAMEN_FISICO_FAILURE =
  "FETCH_LIST_EXAMEN_FISICO_FAILURE";

export const FETCH_LIST_EXAMEN_FISICO_COUNT_INIT =
  "FETCH_LIST_EXAMEN_FISICO_COUNT_INIT";
export const FETCH_LIST_EXAMEN_FISICO_COUNT_SUCCESS =
  "FETCH_LIST_EXAMEN_FISICO_COUNT_SUCCESS";
export const FETCH_LIST_EXAMEN_FISICO_COUNT_FAILURE =
  "FETCH_LIST_EXAMEN_FISICO_COUNT_FAILURE";

export const DELETE_EXAMEN_FISICO_INIT = "  DELETE_EXAMEN_FISICO_INIT";
export const DELETE_EXAMEN_FISICO_SUCCESS = "  DELETE_EXAMEN_FISICO_SUCCESS";
export const DELETE_EXAMEN_FISICO_FAILURE = "  DELETE_EXAMEN_FISICO_FAILURE";

export const RESET_LIST_EXAMEN_FISICO = " RESET_LIST_EXAMEN_FISICO";
export const RESET_MODAL_EXAMEN_FISICO = " RESET_MODAL_EXAMEN_FISICO";
