export const FETCH_GET_OXIMETRIA_INIT = "FETCH_GET_OXIMETRIA_INIT";
export const FETCH_GET_OXIMETRIA_SUCCESS = "FETCH_GET_OXIMETRIA_SUCCESS";
export const FETCH_GET_OXIMETRIA_FAILURE = "FETCH_GET_OXIMETRIA_FAILURE";

export const UPDATE_OXIMETRIA_INIT = "UPDATE_OXIMETRIA_INIT";
export const UPDATE_OXIMETRIA_SUCCESS = "UPDATE_OXIMETRIA_SUCCESS";
export const UPDATE_OXIMETRIA_FAILURE = "UPDATE_OXIMETRIA_FAILURE";

export const RESET_GET_OXIMETRIA = "RESET_GET_OXIMETRIA";
