export const FETCH_GET_EXAMEN_FISICO_INIT = "FETCH_GET_EXAMEN_FISICO_INIT";
export const FETCH_GET_EXAMEN_FISICO_SUCCESS =
  "FETCH_GET_EXAMEN_FISICO_SUCCESS";
export const FETCH_GET_EXAMEN_FISICO_FAILURE =
  "FETCH_GET_EXAMEN_FISICO_FAILURE";

export const UPDATE_EXAMEN_FISICO_INIT = "UPDATE_EXAMEN_FISICO_INIT";
export const UPDATE_EXAMEN_FISICO_SUCCESS = "UPDATE_EXAMEN_FISICO_SUCCESS";
export const UPDATE_EXAMEN_FISICO_FAILURE = "UPDATE_EXAMEN_FISICO_FAILURE";

export const RESET_GET_EXAMEN_FISICO = "RESET_GET_EXAMEN_FISICO";
